name: Push Backend server to EC2

on:
  push:
    branches:
      - main
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: smileyniloc/cradlewave-backend

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: #  Set permissions for connecting to EC2 updating
  id-token: write
  contents: read

jobs:
  build_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Set up Docker Buildx and QEMU for multi-platform builds
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata for image
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./webdev/backend
          file: ./webdev/backend/Dockerfile
          push: true
          # Pick which platforms to build for (amd64 and arm64 for EC2)
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
  run-remote-commands:
    needs: build_push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: us-east-2
          role-session-name: github-actions-ec2

      - name: Set up SSH configuration
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/cradlewave.pem
          chmod 600 ~/.ssh/cradlewave.pem

          cat <<EOF > ~/.ssh/config
          Host cradlewave-ec2
              HostName i-00476f32b32bce525
              User ubuntu
              IdentityFile ~/.ssh/cradlewave.pem
              ProxyCommand aws ec2-instance-connect open-tunnel --instance-id %h --region us-east-2
              StrictHostKeyChecking no
          EOF

      - name: Create Remote Log and update docker container on EC2 instance
        run: |
          ssh cradlewave-ec2 "echo 'Deployment Log - $(date)' > deploy.log"
          ssh cradlewave-ec2 "sudo sed -i 's/nameserver .*/nameserver 2001:67c:2b0::4\nnameserver 2001:67c:2b0::6/' /etc/resolv.conf"
          ssh cradlewave-ec2 "docker pull ghcr.io/smileyniloc/cradlewave-backend:main"
          ssh cradlewave-ec2 "docker stop cradlewave-backend || true && docker rm cradlewave-backend || true"          
          ssh cradlewave-ec2 "docker run -d \
            --name cradlewave-backend \
            --restart unless-stopped \
            -p 8080:8080 \
            -e PORT=8080 \
            ghcr.io/smileyniloc/cradlewave-backend:main"
          ssh cradlewave-ec2 "docker image prune -f"
